/home/users/mhturner/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/users/mhturner/.local/lib/python3.6/site-packages/numpy/core/_methods.py:78: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
Traceback (most recent call last):
  File "/home/users/mhturner/SC-FC/get_region_responses.py", line 35, in <module>
    RegionResponses = pd.Series(data=region_responses, index=rois)
  File "/home/users/mhturner/.local/lib/python3.6/site-packages/pandas/core/series.py", line 249, in __init__
    .format(val=len(data), ind=len(index)))
ValueError: Length of passed values is 75, index implies 35
